### ISSUE TITLE
Request: tag a release

### ISSUE THREAD

**Issue by AkihiroSuda** [compose-spec/compose-go#118]
For ease of dependency management, could you consider creating a release with git tag?

**Comment by AkihiroSuda** [comment]
Linking related discussion : https://github.com/compose-spec/compose-spec/issues/104#issuecomment-816524801

**Comment by alexellis** [comment]
We could really use a release here too @ndeloof for the usage in [faasd](https://github.com/openfaas/faasd)

Recent breaking changes in master the Go library have broken our usage, so we're having to pin to an old commit. It's harder to understand what changes are being made without any versions being cut, so what do you think about starting to create tags?

**Comment by ndeloof** [comment]
I'd like we adopt something extra-simple to define tagged releases. https://github.com/compose-spec/compose-spec/issues/171 is still way too complex imho as it still require maintainers to agree on good time for a release...
I'd suggest we adopt a "Jenkins-style" weekly release cycle, i.e. have a cron job to tag and release `v1.xxx` wdyt?

> it's harder to understand what changes are being made without any versions being cut

**Comment by AkihiroSuda** [comment]
https://github.com/compose-spec/compose-go/releases/tag/v1.0.1 🎉 
Thanks!
