### ISSUE TITLE
Reject a Compose file with unexpected fields

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-go#12]
As Compose specification evolves and introduce new fields/features, a Compose implementation MAY just reject a compose file using a higher level version than the one it has been built on. 

On the other hand, even if a compose file uses a newer version it doesn't mean it also use recent fields, and implementation would not be able to use it.

Last but not least, as we made `version: "3"` and alias for "latest" there's no way to guarantee a Compose file do not target a more recent specification than the one being implemented.

_So_, a Compose implementation need to be able to reject a compose file which uses fields introduced by a newer version of the specification. Schema validation can be used here, but we also can make the code stricter regarding this scenario: mapstructure used internally to map yaml sections into go structs can track unmapped attributes.  We can rely on this to offer informative diagnostic to the end-user.

**Comment by bruno-oliveira** [comment]
I'd like to work on this issue as well :)

**Comment by ndeloof** [comment]
closing as obsolete, as we removed the version requirement
