### ISSUE TITLE
Serialize Go model back to file

### ISSUE THREAD

**Issue by marcauberer** [compose-spec/compose-go#135]
Hi,
is it possible to serialize the Go models back to compose files? If yes, how can this be achieved?

Thanks in advance

**Comment by marcauberer** [comment]
?

**Comment by ndeloof** [comment]
this is indeed a supported usage, that is used for Docker Compose v2: https://github.com/docker/compose-cli/blob/main/local/compose/compose.go#L69-L72

**Comment by ZhuonanLin** [comment]
Hi there, I am dealing with the same situation in my case, i.e., I want to convert a Go `ServiceConfig` struct to yaml compose file, the link above is invalid, can you please give me a new reference? Thanks!

**Comment by ndeloof** [comment]
You just need to run `yaml.Marshal(project)` to get a compose-go project serialized to yaml
