### ISSUE TITLE
Environment Variables Not Replaced

### ISSUE THREAD

**Issue by michaelperel** [compose-spec/compose-go#148]
When using the [loader from compose-go](https://github.com/compose-spec/compose-go/blob/4e2e7e7def77c1c535c6411783ecfbda954a5d62/loader/loader.go#L125), environment variables in the docker-compose file do not get replaced (variables defined with $). However, when using the [loader from the docker cli](https://github.com/docker/cli/blob/12e8782c0cafdc1ea3922cf0323cefc312e41574/cli/compose/loader/loader.go#L64), environment variables do get replaced.

The code in compose-go is quite similar to that in the `docker` cli, so this feels like a bug.

[Here is a repo that reproduces this issue](https://github.com/michaelperel/compose-cli-err).

There are 2 branches - `master` and `old-loader`

`go run main.go` in `master` shows that compose-go does not replace environment variables.

`go run main.go` in `old-loader` shows that the docker-cli loader does replace the environment variables.

The code in `main.go` is the same in both branches. The only difference is the import in `go.mod`.

I would like to replace the docker cli loader in [docker-lock](https://github.com/safe-waters/docker-lock) with compose-go's loader, now that `docker` supports `docker compose`.

**Comment by ndeloof** [comment]
don't invoke `ParseYAML`, just set configFiles as 
```golang
        types.ConfigFile{
			Filename: name,
			Content:  bytes,
		}
```
see `cli.ProjectFromOptions` for reference
