### ISSUE TITLE
Compose handles key-only .env file differently than Docker and Docker-Compose

### ISSUE THREAD

**Issue by flemay** [compose-spec/compose-go#210]
Hi! I have been testing `docker compose` with environment variables and the result differs from Docker and Docker-Compose.

## Test

Define a `.env` file with the following:

```
ENV_A
ENV_B=
ENV_C=env_c
```

And a `docker-compose.yml` file:

```yml
services:
  alpine:
    image: alpine
    env_file: .env
```

### Docker

```bash
$ docker run --rm --env-file=.env alpine env
ENV_B=
ENV_C=env_c
```

Here `ENV_A` has not been set and `ENV_B` is set with an empty value.

### Docker-Compose

```bash
$ docker-compose run --rm alpine env
ENV_B=
ENV_C=env_c
```

With Docker-Compose, we get the same outcome as Docker

### Compose

```bash
$ docker compose run --rm alpine env
ENV_C=env_c
ENV_A=ENV_B=
```

Here's where the outcome is quite unexpected: `ENV_A` is set with the value `ENV_B=`.

Compose seems to have a problem with key-only items in `.env` file.

**Comment by flemay** [comment]
Just realised that this issue could be in https://github.com/docker/compose?

**Comment by flemay** [comment]
Created this PR https://github.com/compose-spec/godotenv/pull/12 :)

**Comment by milas** [comment]
This issue (and many others) should be fixed now. Thanks for reporting and the PR(s) to fix it!
