### ISSUE TITLE
Allow `loader.ParseYAML` and `loader.Load` to use strict YAML unmarshalling

### ISSUE THREAD

**Issue by OrBin** [compose-spec/compose-go#223]
`loader.ParseYAML` (and correspondingly `loader.Load`) use `yaml.Unmarshal`, which performs non-strict YAML unmarshalling (in _yaml.v2_ package), while in some cases a caller would like to perform strict YAML unmarshalling (e.g. to avoid duplicate keys in a map).

Would it be possible to add a `strict` boolean parameter to `loader.ParseYAML` and add a corresponding option to `loader.Load` and  `loader.parseConfig`? I'm willing to do this myself, if possible.

**Comment by ndeloof** [comment]
We could introduce a loader option to force strict parsing, but https://github.com/go-yaml/yaml/blob/v3/yaml.go#L156 is not exported, and AFAICT `strict` parameter is unused (?)
