### ISSUE TITLE
Environment fallback not working in .env file.

### ISSUE THREAD

**Issue by GerbenLimburg** [compose-spec/compose-go#225]
Given system variable SYS_VAR=the_value when set:
and an .env file:
Some__env__var=${SYS_VAR:-fallback}

Using docker-compose v1.29.2, this results in either:
Some__env__var=the_value when SYS_VAR has a value or 
Some__env__var=fallback when SYS_VAR is not set or is empty.

In docker compose v2.2.3 this results in 
Some__env__var=the_value:-fallback when SYS_VAR has a value or
Some__env__var=:-fallback when SYS_VAR is not set or is empty.

To me, the behaviour in v2.2.3 is unexpected.

**Comment by milas** [comment]
This is fixed in more recent versions of Compose v2.

We are also working on clarifying and formalizing the spec here around interpolation behavior, as the spec is currently inaccurate.
