### ISSUE TITLE
Cannot Marshal a `command` as a single string.

### ISSUE THREAD

**Issue by mattdee123** [compose-spec/compose-go#267]
The `command` field of a compose service can be [either a list of strings, or a single string](https://docs.docker.com/compose/compose-file/#command).

This project represents it as
```
// ShellCommand is a string or list of string args
type ShellCommand []string
```
However, there doesn't seem to be a way to marshal it as a single string --it always comes out as a list. Does this mean that only the list form is supported?

**Comment by milas** [comment]
Correct - during unmarshal, a single string will be split:
https://github.com/compose-spec/compose-go/blob/d61c32fedd9fee1bee13efb4040f9125da9483fd/loader/loader.go#L1138-L1143

During marshal, the list form is considered canonical and is always used.
