### ISSUE TITLE
Working with v2 compose files

### ISSUE THREAD

**Issue by kklin** [compose-spec/compose-go#44]
Hi! I'm investigating how I can consume v2 compose files in my application since there's still a lot of them in the wild. (Compose-go has worked great for the v3 Compose files I've tested it on so far!)

I know that the spec is only for v3, but do you all have any advice on how I should approach working with v2 files? I haven't dug too deep yet, but it looks like there's some initial error handling for `extends` and `volumes_from` already that I'd need to disable.

**Comment by ndeloof** [comment]
Based on https://github.com/compose-spec/compose-spec/issues/12 we plan to introduce support for v2 attributes.

**Comment by ndeloof** [comment]
Closing as compose-spec supports all compose v2 and v3 attributes
