### ISSUE TITLE
Converting ports from short to long syntax should not assume "ingress"

### ISSUE THREAD

**Issue by lionello** [compose-spec/compose-go#458]
https://github.com/compose-spec/compose-go/blob/ba097a5dee2003644e4b172f63afbdb5a613b29c/types/types.go#L800

Nowhere in the spec does it specify the default mode for a port that's using the short syntax, so I'd expect the `Mode` member to have the default (empty) value after conversion. 

Similarly, not specifying a protocol in the short syntax results in `Protocol` "tcp", but the spec says the default is ["any protocol."](https://github.com/compose-spec/compose-spec/blob/6042e09837df4539fdc539890f0ab868e2aa76ec/05-services.md?plain=1#L1372) This bug is because of the following line in the `nat` module:

https://github.com/docker/go-connections/blob/master/nat/nat.go#L102C21-L102C21

**Comment by ndeloof** [comment]
I prefer we fix the spec to match `docker run -p ...` behavior so Docker Compose user don't get into weird issues with compose to configure ports in some unexpected way due to non-consistent defaults

**Comment by lionello** [comment]
@ndeloof Docker doesn't have ingress, so that would imply `host` mode as well.

**Comment by ndeloof** [comment]
non-swarm docker engine is single node and then those are just the same

**Comment by lionello** [comment]
@ndeloof the problem is that most ingress controllers won't let you map any host port to any ingress port, so it often doesn't make sense to consider `- "1234:1234"` to mean "ingress on 1234 mapped to host port 1234".

**Comment by ndeloof** [comment]
>  it often doesn't make sense to consider - "1234:1234" to mean "ingress on 1234 mapped to host port 1234".

it doesn't, it just means "_ingress on 1234 mapped to **container** port 1234_"

**Comment by ndeloof** [comment]
> I find it surprising that ...

sure, this is `docker run` legacy

**Comment by lionello** [comment]
> > it often doesn't make sense to consider - "1234:1234" to mean "ingress on 1234 mapped to host port 1234".
> 
> it doesn't, it just means "_ingress on 1234 mapped to **container** port 1234_"

You’re right, that’s what I meant.

What to do when a host IP is mentioned in the short syntax? Surely that means host mode.
