### ISSUE TITLE
Project name not checked when using ToConfigFiles

### ISSUE THREAD

**Issue by aksiksi** [compose-spec/compose-go#489]
`ToConfigFiles` does not read the content of the Compose files. In the `loader.projectName` function when checking for the existence of the top-level "name" key, the `Content` field is not set, so the read fails silently and never actually checks the "name" value.

https://github.com/compose-spec/compose-go/blob/main/loader/loader.go#L482

A workaround is to explicitly set the `Content` field instead of using `ToConfigFiles`.

**Comment by ndeloof** [comment]
Can you propose a pull-request with your fix?
