### ISSUE TITLE
Environment copied before being mutated

### ISSUE THREAD

**Issue by lionello** [compose-spec/compose-go#520]
This line initializes the `Environment`, when not initialized by the caller:
https://github.com/compose-spec/compose-go/blob/8585af8ec50b47489c1e7304dde3a7577aa658e4/loader/loader.go#L269

But the environment gets copied (implicitly) earlier on this line:
https://github.com/compose-spec/compose-go/blob/8585af8ec50b47489c1e7304dde3a7577aa658e4/loader/loader.go#L249

So, when `Environment` is `nil`, the set of `COMPOSE_PROJECT_NAME` in the map is not visible by the call to `LookupValue`.

A potential fix is to change `func (cd ConfigDetails) LookupEnv(…)` to a pointer receiver to avoid the copy.

**Comment by ndeloof** [comment]
I don't get it. we capture `LookupEnv` func, so actually the `configDetails` _receiver_, then when executed this function will access receiver field `Environment`, even this one was set _after_.
Please provide an illustration example (either code or docker compose usage) to demonstrate a bug
