### ISSUE TITLE
Marshalling produces invalid compose file

### ISSUE THREAD

**Issue by azukaar** [compose-spec/compose-go#521]
Using project.MarshalYAML() with extra_hosts causes invalid output

ex. 

```
    extra_hosts:
      - host.docker.internal:host-gateway
```

will give

```
    extra_hosts:
    - host.docker.internal=host-gateway
```

which produces an error because docker compose expect the ip after :

the fix would be to change = to : in here https://github.com/compose-spec/compose-go/blob/main/types/hostList.go#L43

**Comment by jhrotko** [comment]
Hello, @azukaar 

could you please specify what you are trying to do/accomplish?

**Comment by ndeloof** [comment]
This change is intentional, see https://github.com/docker/cli/issues/4648

> which produces an error because docker compose expect the ip after :

That's not the case running latest Docker Compose.
