### ISSUE TITLE
compose-go should resolve all relative paths

### ISSUE THREAD

**Issue by ndeloof** [compose-spec/compose-go#57]
For all attribute which support relative paths by Compose-specification, compose-go should offer a way to resolve relative paths so that Compose implementations get a complete model. Can at same time detect missing files.

reminder: 
- relative paths MUST be resolved based on (first) compose file working directory
- path starting by `.` MUST be resolved based on ~process working directory (os.Getwd)~ compose project working directory, i.e. `compose.yaml` parent folder or path explicitly set by user as project directory.
- path starting by `~/` MUST be resolved based on user's home directory (`os.UserHomeDir`)

**Comment by kklin** [comment]
> path starting by . MUST resolve from process working directory (os.Getwd)

I believe that for bind volumes defined in the service, the source path has to start with a `./`, and it resolves relative to the compose file. E.g.
```
services:
  web:
    image: nginx
    volumes:
      - './foo:/bar'
```

**Comment by ndeloof** [comment]
Good catch, `docker-compose` indeed resolves `.` based on compose file's parent folder, not working directory the command is ran from.
see https://github.com/docker/compose/blob/master/compose/config/config.py#L758-L759 where `config_details.working_dir` is set from compose file's parent folder (https://github.com/docker/compose/blob/master/compose/config/config.py#L304) or path set by `--project-directory`, not working directory the docker-compose command is ran from.

I'm updating this issue accordingly, thanks

**Comment by kklin** [comment]
No problem -- very cool that you know the compose source so well! I just know bits and pieces through trial and error 😄

**Comment by ndeloof** [comment]
both approaches are complimentary :)
