### ISSUE TITLE
WithOsEnv assumes wrongly that os.Environ() returns only strings containing an equal sign

### ISSUE THREAD

**Issue by apostasie** [compose-spec/compose-go#639]
https://github.com/compose-spec/compose-go/blob/main/cli/options.go#L240

This will call `GetAsEqualsMap` which will throw with an index out of bound in case a string does not contain an equal sign.

(we did hit that with a broken test in nerdctl - https://github.com/containerd/nerdctl/pull/3111)

**Comment by ndeloof** [comment]
In which circumstances does os.Envrion _not_ return an equals sign? 
That's not clearly described by https://pkg.go.dev/os#Environ

**Comment by apostasie** [comment]
Thanks for fixing this @ndeloof 

FWIW, a quick repro here: https://go.dev/play/p/JQw_6OA2--s

**Comment by ndeloof** [comment]
sure, but I wonder in which real circumstances os.Environ() would return a string without `=` sign.

**Comment by apostasie** [comment]
> sure, but I wonder in which real circumstances os.Environ() would return a string without `=` sign.

I see your point. Agreed that it "should not happen under real/normal circumstances".
