### ISSUE TITLE
Dashes in variable names <=> `environment:` block

### ISSUE THREAD

**Issue by simonhammes** [compose-spec/compose-go#663]
Dashes can be used in variable names (https://github.com/compose-spec/compose-go/pull/336).

However, I'm unable to use a variable that contains dashes in an `environment:` block since `compose` interprets the dash as a separator between the variable name and its default value:

```yml
environment:
  VAR-WITH-DASHES: ${VAR-WITH-DASHES}
```

Is there any way to escape the dash or is this a bug/unimplemented functionality?

**Comment by ndeloof** [comment]
`-` indeed is delimiter for default value, which makes #336 actually irrelevant 😓 
I guess we should revert, as this issue demonstrate this "feature" was incomplete and can't be used anyway
cc @jhrotko @glours

**Comment by KasonBraley** [comment]
@glours Can this bug fix be released in a patch so [compose](https://github.com/docker/compose) can release a version with the fix?

**Comment by ndeloof** [comment]
no worries, this will be part of the next compose release coming soon.
Cheers
