### ISSUE TITLE
compose up problem with sdk

### ISSUE THREAD

**Issue by sysnasri** [compose-spec/compose-go#677]
Hi, After a few days of working on compose-go sdk, I would like to ask you why my code can't start a compose-file? 

something I found out, that there is not api.CreateOptions in the base code! 

![Screenshot 2024-08-26 at 16 07 42](https://github.com/user-attachments/assets/4272d8fc-7f52-4a06-8e34-cd486c6d7e9a)

```
func ComposeProjectCreation(p string, cf string) {

	ctx, _, dcli, err := DockerClientInit()
	CheckErr("Faild to initialize Docker client %v", err)

	//dcs := compose.NewComposeService(dcli)

	ops, err := cli.NewProjectOptions(
		[]string{cf},
		cli.WithOsEnv,
		cli.WithDotEnv,
		cli.WithName(p),
	)

	CheckErr("erro", err)
	pr, err := ops.LoadProject(ctx)
	CheckErr("error", err)
	pryml, err := pr.MarshalYAML()
	fmt.Println(string(pryml))

	cs := compose.NewComposeService(dcli)
	err = cs.Up(ctx, pr, api.UpOptions{
		Start: api.StartOptions{
			Project: pr,
		},
	})
	CheckErr("Failed to bring up the project", err)
}
```

**Comment by ndeloof** [comment]
compose-go only supports parsing compose file into a go model. To reuse Docker Compose implementation of the `up` command and lifecycle management, you'll need https://github.com/docker/compose/blob/main/pkg/api/api.go#L185
