### ISSUE TITLE
Regression: no longer able to use custom interpolation

### ISSUE THREAD

**Issue by lionello** [compose-spec/compose-go#710]
This code used to work but broke after c558adc510603a923d7b4d15eca74152529b2a5b :

```go
	return cli.NewProjectOptions(configPaths,
		…
		cli.WithLoadOptions(func(o *loader.Options) {
			// Panic: o.Interpolate is `nil` now
			o.Interpolate.Substitute = func(templ string, mapping template.Mapping) (string, error) {…},
		}))
```
The `WithLoadOptions` callback is being called sooner than before, when `o.Interpolate` is `nil`. It used to be initialized with the loaded environment, but there's no way to access that environment now. Creating an empty `o.Interpolate = &interpolate.Options{}` ends up without any of the loaded environment and reverts to `os.LookupEnv`.

**Comment by ndeloof** [comment]
`cli.WithXX` functional args are indeed ran first as we resolve `--file` into actual local file (can now be a plain Git or OCI reference). This is actually only used to allow `ResourceLoaders` to be set. AFAICT you could just return early if `Interpolate` is nil, a second call as we actually parse the file content will use a fully initialized `Options`.
